cargo publish --no-verify --manifest-path ..\..\Nature-Common\Cargo.toml
cargo publish --no-verify --manifest-path ..\..\Nature-DB\Cargo.toml
cargo publish --no-verify --manifest-path ..\Cargo.toml
cargo publish --no-verify --manifest-path ..\..\Nature-Retry\Cargo.toml
cargo publish --no-verify --manifest-path ..\..\Nature-Demo-Common\Cargo.toml
cargo publish --no-verify --manifest-path ..\..\Nature-Demo-Executor\Cargo.toml
cargo publish --no-verify --manifest-path ..\..\Nature-Demo\Cargo.toml
cargo publish --no-verify --manifest-path ..\..\Nature-Demo-Executor-Restful\Cargo.toml
cargo publish --no-verify --manifest-path ..\..\Nature-Integrate-Test-Executor\Cargo.toml
