// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DomainMode: typeof import('./components/DomainMode.vue')['default']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    InstanceList: typeof import('./components/instance/InstanceList.vue')['default']
    InstanceProperty: typeof import('./components/instance/InstanceProperty.vue')['default']
    LogoMenu: typeof import('./components/LogoMenu.vue')['default']
    MetaProperty: typeof import('./components/meta/MetaProperty.vue')['default']
    MetaTool: typeof import('./components/meta/MetaTool.vue')['default']
    MetaTree: typeof import('./components/meta/MetaTree.vue')['default']
    ModeTool: typeof import('./components/ModeTool.vue')['default']
    RelationEditor: typeof import('./components/relation/RelationEditor.vue')['default']
    RelationList: typeof import('./components/relation/RelationList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
