// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DomainMode: typeof import('./components/meta/DomainMode.vue')['default']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    InstanceList: typeof import('./components/instance/InstanceList.vue')['default']
    InstanceMode: typeof import('./components/instance/InstanceMode.vue')['default']
    InstanceProperty: typeof import('./components/instance/InstanceProperty.vue')['default']
    MetaBaseProperty: typeof import('./components/meta/MetaBaseProperty.vue')['default']
    MetaExtendProperty: typeof import('./components/meta/MetaExtendProperty.vue')['default']
    MetaTool: typeof import('./components/meta/MetaTool.vue')['default']
    MetaTree: typeof import('./components/meta/MetaTree.vue')['default']
    ModeHeader: typeof import('./components/ModeHeader.vue')['default']
    ModeTool: typeof import('./components/ModeTool.vue')['default']
    RelationDiagram: typeof import('./components/relation/RelationDiagram.vue')['default']
    RelationEditor: typeof import('./components/relation/RelationEditor.vue')['default']
    RelationMode: typeof import('./components/relation/RelationMode.vue')['default']
    RelationProperty: typeof import('./components/relation/RelationProperty.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
