@startuml
hide footbox


[->IncomeController: input(instance)
activate IncomeController
IncomeController -> Instance: init to `Business` \nfor `ThingType
IncomeController -> Instance: check and fix id
note right: `meta` maybe not exists
IncomeController -> TaskForStore: gen_task(instance)
IncomeController -> RawTask: save(task)
note right: can redo when failed
IncomeController -> Instance: save(instance)
IncomeController --\\ InnerController: stored(task)
note right #aqua : async \nno mission will exit
deactivate IncomeController


activate InnerController
InnerController -> ConverterInfo: gen_task
InnerController -> RawTask: save_batch
loop each convert info
    InnerController --\\ CallOutParaWrapper:gen_and_call_out
    note left #aqua : async: call out to convert
    InnerController -> Converted :gen
    InnerController -> PlanInfo : save
end

loop each plan
    InnerController --\\ TaskForStore: gen_task(instance)
    InnerController --\\ RawTask: new(task)
end
InnerController -> RawTask: save_batch

loop each instance
InnerController -> Instance: save(instance)
end
deactivate InnerController

@enduml