use super::*;


pub struct CarrierDaoService;

impl CarrierDao for CarrierDaoService {
    /// ID generated by hash
    fn insert<T: Sized + Serialize>(_carrier: &Carrier<T>) -> Result<UuidBytes> {
        unimplemented!()
    }
    fn delete(_id: &UuidBytes) -> Result<()> {
        unimplemented!()
    }
    fn move_to_error<T: Sized + Serialize>(_err: CarryError<T>) -> Result<()> {
        unimplemented!()
    }
    fn update_execute_time(_id: UuidBytes, _new_time: i64) -> Result<()> {
        unimplemented!()
    }
    fn get<T: Sized + Serialize>(_id: UuidBytes) -> Result<Carrier<T>> {
        unimplemented!()
    }
}