use super::*;


pub struct CarrierDaoService;

impl CarrierDao for CarrierDaoService {
    /// ID generated by hash
    fn insert<T: Sized + Serialize>(_carrier: &Carrier<T>) -> Result<UuidBytes> {
        unimplemented!()
    }
    fn delete(_id: &UuidBytes) -> Result<()> {
        unimplemented!()
    }
}