@startuml
' receive request from outside of `Nature`
namespace rpc {
    namespace rocket{
        class server
    }
}

namespace task {
    class IncomeController
    class ControllerImpl
    note top: "all services initialized here"
}

namespace DB{
    class InstanceSvc
}

namespace channels {

}

namespace support {

}


@enduml