@startuml
hide footbox
[->rpc.rocket.server: input(instance)
rpc.rocket.server -> StoreSvc: input(instance)
StoreSvc -> TaskSvc: create task for store
activate StoreSvc
StoreSvc -> StoreSvc: init to `Business` \nfor `ThingType`
StoreSvc -> InstanceSvc: verify
note left: maybe not exists
StoreSvc -> RouteSvc: get missions
StoreSvc -> StoreSvc: save instance
StoreSvc --\\ InnerController: instance stored
note right #aqua : async \nno mission will exit
deactivate StoreSvc
activate InnerController
InnerController -> ConverterSvc: generate convert information
note left: maybe many
InnerController -> TaskSvc: create new tasks and finish prior task
loop each convert info
    InnerController --\\ InnerController: convert
    note left #aqua : async: call out to convert
    activate InnerController
    InnerController -> ConverterSvc: convert
    activate ConverterSvc
    deactivate InnerController
end
deactivate InnerController
ConverterSvc -> InstanceSvc: verify
ConverterSvc -\\ InnerController: converted
deactivate ConverterSvc
note left #aqua : async
activate InnerController
InnerController -> PlanSvc: save
loop each plan
    InnerController -> StoreSvc: generate task for store
end
InnerController -> TaskSvc: create new tasks and finish prior task
loop each task
    InnerController -\\ InnerController: to store
    note left #aqua : async
    InnerController -> StoreSvc: save instance
end


@enduml