@startuml

class Order

Enum OrderStatus{
    new
    payed
    stock removing
    shipping
    finished
}

class Payment

class ReleaseApplication

class OutboundOrder

class DeliverApplication

class ReceiptForm



@enduml