POST
http://localhost:8180/instance/byId
@Content-Type: application/json
{
    "id": "14988181541190564681",
    "meta": "B:finance/payment:1",
    "para": "",
    "state_version": 0
}

%%%
# Duration: 21 ms
# POST
# http://localhost:8180/instance/byId
# Headers
# @Content-Type: application/json
# Body
# {
#     "id": "14988181541190564681",
#     "meta": "B:finance/payment:1",
#     "para": "",
#     "state_version": 0
# }


# status 200

@content-length: 265
@content-type: application/json
@date: Fri, 12 Feb 2021 13:18:27 GMT

{"Ok":{"id":"14988181541190564681","data":{"meta":"B:finance/payment:1","content":"{\"order\":\"10071269418607538781\",\"from_account\":\"c\",\"paid\":700,\"pay_time\":1613131828711}","sys_context":{"target.id":"10071269418607538781"}},"create_time":1613131828000}}
